# Generated by Django 5.2.8 on 2026-09-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_timelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('hourly_learning', 'Hourly Learning Video Recording'), ('per_minute_reels', 'Per-Minute Reels'), ('outdoor_shoot', 'Outdoor Shoot')], max_length=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='unit',
            field=models.CharField(choices=[('hour', 'Hour'), ('minute', 'Minute'), ('session', 'Session')], max_length=20),
        ),
    ]
