# Generated by Django 5.2.8 on 2026-09-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clienttag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('teacher', 'Teacher'), ('professor', 'Professor'), ('lab', 'Laboratory'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
