import React, {useState} from 'react';
import { Alert, Button, Card, Dialog, DialogTitle, DialogContent, DialogActions, Grid, Skeleton, Stack, Typography } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import api from '../api/client';
import { useAuth } from '../contexts/AuthContext';
export default function StudioToday() {
 const {user}=useAuth(),{i18n}=useTranslation(),ar=i18n.language==='ar';
 const t=(en:string,arabic:string)=>ar?arabic:en;
 const allowed=['owner','admin'].includes(user?.role);const [record,setRecord]=useState<any>(null);
 const {data,error,isLoading,refetch}=useQuery({queryKey:['studio-today'],queryFn:()=>api.get('/studio/operations').then(r=>r.data),enabled:allowed,refetchInterval:60000});
 const requests=useQuery({queryKey:['studio-today-requests'],queryFn:()=>api.get('/studio/requests').then(r=>r.data.results),enabled:allowed,refetchInterval:60000});
 if(!allowed)return null;
 const metrics=[{label:t('Today’s shoots','تصوير اليوم'),value:data?.shoots?.length,path:'/schedule'}, {label:t('Outstanding orders','طلبات غير مدفوعة'),value:data?.unpaid?.length,path:'/orders'}, {label:t('Recordings in review','تسجيلات للمراجعة'),value:data?.review?.length,path:'/delivery'}, {label:t('Collected this month / EGP','المقبوض هذا الشهر / جنيه'),value:data?.cash_month,path:'/payments'}];
 const groups=[{title:t('Next shoots','التصوير القادم'),path:'/schedule',items:(data?.upcoming||[]).slice(0,4),label:(x:any)=>`${x.client_name} · ${new Date(x.start_time).toLocaleString(ar?'ar-EG':'en-GB',{timeZone:'Africa/Cairo'})} · ${x.status}`}, {title:t('Outstanding balances','أرصدة مستحقة'),path:'/orders',items:(data?.unpaid||[]).slice(0,4),label:(x:any)=>`${x.order_number} · ${x.client_name} · ${x.remaining_balance} EGP`}, {title:t('Review queue','قائمة المراجعة'),path:'/delivery',items:(data?.review||[]).slice(0,4),label:(x:any)=>`${x.title} · ${x.client_name} · ${x.state}` }];
 return <Stack spacing={2} sx={{mb:4}}><Stack direction="row" alignItems="center" justifyContent="space-between"><Typography variant="h5">{t('Today at SMART SHOOTS','اليوم في SMART SHOOTS')}</Typography><Button href="/studio">{t('Studio control','إدارة الاستوديو')} ↗</Button></Stack>
 {error&&<Alert severity="error" action={<Button onClick={()=>refetch()}>{t('Retry','حاول مجددًا')}</Button>}>{t('Overview unavailable. Values are not shown until refreshed.','الملخص غير متاح. تظهر القيم بعد التحديث.')}</Alert>}
 <Grid container spacing={2}>{metrics.map(m=><Grid item xs={6} md={3} key={m.path}><Card sx={{p:2.5,bgcolor:'#10233d',color:'#fff',borderRadius:3,boxShadow:'0 6px 0 #071426'}}><Typography sx={{color:'#c8d6e7',fontSize:13}}>{m.label}</Typography>{isLoading?<Skeleton height={48}/>:<Typography variant="h4" sx={{color:'#edcf89'}}>{error?'—':m.value??'—'}</Typography>}<Button href={m.path} sx={{color:'#fff',mt:1}}>{t('Open','فتح')} ↗</Button></Card></Grid>)}</Grid>
 {!error&&<Grid container spacing={2}>{groups.map(g=><Grid item xs={12} md={4} key={g.path}><Card sx={{p:2.5,height:'100%',borderRadius:3}}><Typography variant="h6">{g.title}</Typography>{isLoading?<Skeleton height={100}/>:g.items.length?g.items.map((x:any)=><Button key={x.id} onClick={()=>setRecord({item:x,path:g.path,title:g.title,summary:g.label(x)})} sx={{display:'block',textAlign:'start',width:'100%',py:1.5,borderBottom:'1px solid #d9e0e8'}}>{g.label(x)}</Button>):<Typography sx={{py:2}} color="text.secondary">{t('Nothing waiting here.','لا توجد عناصر هنا.')}</Typography>}<Button href={g.path}>{t('View all','عرض الكل')} ↗</Button></Card></Grid>)}</Grid>}
 <Card sx={{p:2.5,borderRadius:3}}><Typography variant="h6">{t('Recent shoot requests','طلبات التصوير الأخيرة')}</Typography>{requests.isLoading?<Skeleton height={80}/>:requests.error?<Alert severity="warning">{t('Requests could not load. Open Studio control to retry.','تعذر تحميل الطلبات. افتح إدارة الاستوديو.')}</Alert>:requests.data?.length?requests.data.slice(0,5).map((r:any)=><Button key={r.id} href={'/studio?tab=4&request='+encodeURIComponent(r.id)} sx={{display:'block',textAlign:'start',py:1}}>{r.name} · {r.state} · {r.data?.date||t('Date to discuss','موعد للمناقشة')}</Button>):<Typography color="text.secondary" sx={{py:2}}>{t('New enquiries appear here when public requests are enabled.','تظهر الاستفسارات هنا عند تفعيل الطلبات العامة.')}</Typography>}<Button href="/studio?tab=4">{t('Requests & shoot checklist','الطلبات وقائمة التصوير')} ↗</Button></Card><Dialog open={!!record} onClose={()=>setRecord(null)} fullWidth maxWidth="sm"><DialogTitle>{record?.title}</DialogTitle><DialogContent><Typography sx={{mb:2}}>{record?.summary}</Typography><Typography color="text.secondary">{t('Record ID','رقم السجل')}: {record?.item.id}</Typography>{record?.item.title&&<Typography>{record.item.title}</Typography>}{record?.item.status&&<Typography>{t('Status','الحالة')}: {record.item.status}</Typography>}{record?.item.state&&<Typography>{t('Review state','حالة المراجعة')}: {record.item.state}</Typography>}{record?.item.remaining_balance&&<Typography>{t('Outstanding / EGP','المستحق / جنيه')}: {record.item.remaining_balance}</Typography>}</DialogContent><DialogActions><Button onClick={()=>setRecord(null)}>{t('Close','إغلاق')}</Button><Button href={record?.path||'/studio'}>{t('Open management screen','فتح شاشة الإدارة')} ↗</Button></DialogActions></Dialog></Stack>;
}
