# Generated by Django 5.2.8 on 2026-09-07 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='method',
            field=models.CharField(choices=[('purchasing', 'Purchasing'), ('withdraw', 'Withdraw')], default='purchasing', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Mobile number must be 11 digits and start with 010, 011, 012, or 015.', regex='^(010|011|012|015)\\d{8}$')]),
        ),
    ]
