# Generated by Django 5.2.8 on 2026-09-07 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clienttag_client_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('business', 'Business')], default='academic', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name must contain letters only (no numbers or symbols).', regex="^[A-Za-z\\u0600-\\u06FF][A-Za-z\\u0600-\\u06FF\\s'\\-]*$")]),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Mobile number must be 11 digits and start with 010, 011, 012, or 015.', regex='^(010|011|012|015)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Mobile number must be 11 digits and start with 010, 011, 012, or 015.', regex='^(010|011|012|015)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Name must contain letters only (no numbers or symbols).', regex="^[A-Za-z\\u0600-\\u06FF][A-Za-z\\u0600-\\u06FF\\s'\\-]*$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Name must contain letters only (no numbers or symbols).', regex="^[A-Za-z\\u0600-\\u06FF][A-Za-z\\u0600-\\u06FF\\s'\\-]*$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Mobile number must be 11 digits and start with 010, 011, 012, or 015.', regex='^(010|011|012|015)\\d{8}$')]),
        ),
    ]
