# Generated by Django 5.2.8 on 2026-09-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_category_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienttag',
            options={'ordering': ['name']},
        ),
    ]
