# Generated by Django 6.1.1 on 2026-09-05 08:05

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('staff', 'Staff'), ('equipment', 'Equipment'), ('venue', 'Venue'), ('vehicle', 'Vehicle')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#4A90E2', max_length=7)),
                ('capacity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('block_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('vacation', 'Vacation'), ('holiday', 'Holiday'), ('other', 'Other')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='scheduling.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField(editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('buffer_before', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('buffer_after', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='accounts.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='production.productionorder')),
                ('resources', models.ManyToManyField(related_name='appointments', to='scheduling.resource')),
            ],
            options={
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='scheduling__start_t_fa35ea_idx'), models.Index(fields=['status'], name='scheduling__status_1008cc_idx')],
            },
        ),
    ]
