# Generated by Django 5.2.8 on 2026-09-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='scheduling.resource'),
        ),
    ]
