# Generated by Django 6.1.1 on 2026-09-05 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_browser', models.BooleanField(default=True)),
                ('enable_pwa', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('schedule_conflicts', models.BooleanField(default=True)),
                ('upcoming_sessions', models.BooleanField(default=True)),
                ('new_deposits', models.BooleanField(default=True)),
                ('outstanding_balances', models.BooleanField(default=True)),
                ('pending_production', models.BooleanField(default=True)),
                ('delivery_status', models.BooleanField(default=True)),
                ('operational_reminders', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('schedule_conflict', 'Schedule Conflict'), ('upcoming_session', 'Upcoming Session'), ('new_deposit', 'New Deposit'), ('outstanding_balance', 'Outstanding Balance'), ('pending_production', 'Pending Production Task'), ('delivery_status', 'Delivery Status Update'), ('operational_reminder', 'Operational Reminder')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('message_ar', models.TextField(blank=True)),
                ('deep_link', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['idempotency_key'], name='notificatio_idempot_aa93f8_idx')],
            },
        ),
    ]
