# Generated by Django 5.2.8 on 2026-09-13 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0003_alter_package_type_alter_package_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('cold_outreach', 'Cold Outreach'), ('follow_up', 'Follow-Up'), ('quote_pricing', 'Quote / Pricing'), ('objection_handling', 'Objection Handling'), ('renewal', 'Renewal / Retention'), ('referral', 'Referral Ask'), ('social_caption', 'Social Media Caption')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_type', models.CharField(help_text='e.g. doctor, teacher, professor, lab', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('typical_needs', models.TextField(help_text='What this category usually needs, in plain language.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recommended_packages', models.ManyToManyField(blank=True, related_name='service_profiles', to='production.package')),
                ('suggested_script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for_profiles', to='toolkit.scripttemplate')),
            ],
            options={
                'ordering': ['client_type', 'title'],
            },
        ),
    ]
