# Generated by Django 5.2.8 on 2026-09-26 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('medical', 'Medical / Clinic'), ('multi_category', 'Multi-Category Accreditation'), ('business', 'Business Proposal'), ('education', 'Education'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(upload_to='report_drafts/%Y/%m/')),
                ('file_type', models.CharField(blank=True, choices=[('html', 'HTML'), ('doc', 'Word (.doc)'), ('docx', 'Word (.docx)')], editable=False, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
