import {fail} from './core.js';
const sql=(env,q,...args)=>env.DB.prepare(q).bind(...args);
const first=(env,q,...args)=>sql(env,q,...args).first();
const rows=async(env,q,...args)=>(await sql(env,q,...args).all()).results;
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
function view(p,publicOnly=false){const {photo_key,photo_type,...v}=p;v.photo_url=photo_key?`/api/academy/${publicOnly?'photos':'profiles'}/${p.id}${publicOnly?'':'/photo'}`:null;if(publicOnly){delete v.is_published;delete v.updated_at;}return v;}
async function photo(env,p){if(!p?.photo_key)fail(404,'Photo not found');const obj=await env.FILES.get(p.photo_key);if(!obj)fail(404,'Photo not found');return new Response(obj.body,{headers:{'Content-Type':p.photo_type,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}
export async function academyPublic(req,env){const path=new URL(req.url).pathname.replace(/\/+$/,'');if(path==='/api/academy/public'){if(req.method!=='GET')fail(405,'Method not allowed');return json({results:(await rows(env,'SELECT p.*,c.slug,c.university,c.experience,c.language,c.verified FROM academy_profiles p LEFT JOIN academy_credentials c ON c.profile_id=p.id WHERE p.is_published=1 ORDER BY p.name')).map(p=>view(p,true))});}const match=path.match(/^\/api\/academy\/photos\/([^/]+)$/);if(match){if(req.method!=='GET')fail(405,'Method not allowed');return photo(env,await first(env,'SELECT * FROM academy_profiles WHERE id=? AND is_published=1',match[1]));}return null;}
export async function academyRoute(req,env,user){const path=new URL(req.url).pathname.replace(/\/+$/,'');if(!path.startsWith('/api/academy/'))return null;if(!['owner','admin'].includes(user.role))fail(403,'Administrator access required');const method=req.method;
 if(path==='/api/academy/profiles'&&method==='GET')return json({results:(await rows(env,'SELECT * FROM academy_profiles ORDER BY name')).map(p=>view(p))});
 const match=path.match(/^\/api\/academy\/profiles(?:\/([^/]+))?(?:\/(photo))?$/);if(!match)fail(404,'Endpoint not found');const id=match[1],existing=id?await first(env,'SELECT * FROM academy_profiles WHERE id=?',id):null;if(id&&!existing)fail(404,'Profile not found');
 if(match[2]){if(method==='GET')return photo(env,existing);if(method!=='POST')fail(405,'Method not allowed');const declared=Number(req.headers.get('Content-Length'));if(declared>6*1024*1024)fail(413,'Photo exceeds 5 MiB');const form=await req.formData(),file=form.get('file');if(!file||typeof file==='string'||file.size>5*1024*1024||!file.size)fail(400,'Choose a JPEG, PNG or WebP photo up to 5 MiB');const data=new Uint8Array(await file.arrayBuffer());let type;if(data[0]===255&&data[1]===216&&data[2]===255)type='image/jpeg';else if(data.slice(0,8).join(',')==='137,80,78,71,13,10,26,10')type='image/png';else if(new TextDecoder().decode(data.slice(0,4))==='RIFF'&&new TextDecoder().decode(data.slice(8,12))==='WEBP')type='image/webp';if(!type)fail(400,'Photo must be JPEG, PNG or WebP');const key='academy/'+id+'/'+crypto.randomUUID();await env.FILES.put(key,data,{httpMetadata:{contentType:type}});try{await sql(env,'UPDATE academy_profiles SET photo_key=?,photo_type=?,updated_at=? WHERE id=?',key,type,new Date().toISOString(),id).run();}catch(e){await env.FILES.delete(key);throw e;}if(existing.photo_key)await env.FILES.delete(existing.photo_key);return json(view({...existing,photo_key:key,photo_type:type}));}
 if(method==='DELETE'&&id){await sql(env,'DELETE FROM academy_profiles WHERE id=?',id).run();if(existing.photo_key)await env.FILES.delete(existing.photo_key);return new Response(null,{status:204});}
 if(method!=='POST'&&method!=='PATCH'||method==='PATCH'&&!id||method==='POST'&&id)fail(405,'Method not allowed');let b;try{b=await req.json();}catch{fail(400,'Invalid JSON');}const value={...existing,...b};const text=(key,max)=>String(value[key]||'').trim().slice(0,max);const name=text('name',120),speciality=text('speciality',120);if(!name||!speciality)fail(400,'Name and speciality are required');const programs=Number(value.programs||0),recordings=Number(value.recordings||0),hours=Number(value.hours||0);if(![programs,recordings].every(n=>Number.isSafeInteger(n)&&n>=0&&n<=100000)||!Number.isFinite(hours)||hours<0||hours>100000)fail(400,'Enter valid non-negative activity figures');const record={id:id||crypto.randomUUID(),name,speciality,bio_en:text('bio_en',600),bio_ar:text('bio_ar',600),dedication:text('dedication',350),programs,recordings,hours:Math.round(hours*10)/10,photo_key:existing?.photo_key||null,photo_type:existing?.photo_type||null,is_published:value.is_published===true||value.is_published===1?1:0,updated_at:new Date().toISOString()};const keys=Object.keys(record);await sql(env,`INSERT INTO academy_profiles(${keys.join(',')}) VALUES (${keys.map(()=>'?').join(',')}) ON CONFLICT(id) DO UPDATE SET ${keys.filter(k=>k!=='id').map(k=>k+'=excluded.'+k).join(',')}`,...keys.map(k=>record[k])).run();return json(view(record),id?200:201);
}
export async function academyBackup(env){const profiles=await rows(env,'SELECT * FROM academy_profiles');await env.FILES.put('backups/academy-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({profiles}),{httpMetadata:{contentType:'application/json'}});}
