import schema from './schema.json' with { type: 'json' };
import {fail,HttpError,scaled,money,orderTotal,seconds,interval,digest,equal,passwordHash,verifyPassword} from './core.js';
const enc=new TextEncoder(), now=()=>new Date().toISOString(), uuid=()=>crypto.randomUUID();
const q=n=>'"'+n+'"', json=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...h}});
const stmt=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
const all=async(env,sql,...args)=>(await stmt(env,sql,...args).all()).results;
const first=(env,sql,...args)=>stmt(env,sql,...args).first();
const admin=u=>{if(!['owner','admin'].includes(u.role))fail(403,'Administrator access required');};
function userView(u){const {password,...v}=u;return v;}
async function authenticate(req,env){const t=req.headers.get('Authorization')?.match(/^(?:Token|Bearer) (.+)$/)?.[1]||req.headers.get('Cookie')?.match(/(?:^|;\s*)ss_session=([^;]+)/)?.[1];if(!t)fail(401,'Login required');const u=await first(env,'SELECT u.* FROM sessions s JOIN accounts_user u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.is_active=1',await digest(t),Date.now());if(!u)fail(401,'Session expired. Please log in again');return u;}
async function body(req){if(req.headers.get('Content-Type')?.includes('multipart/form-data'))return req.formData();try{return await req.json();}catch{fail(400,'Invalid JSON request');}}
function defaults(meta){const d={};for(const [n,f] of Object.entries(meta.fields)){if(f.type==='ManyToManyField')continue;if(f.generate==='uuid')d[n]=uuid();else if(f.generate==='now')d[n]=now();else if('default' in f)d[n]=f.default;else if(f.null)d[n]=null;else if(f.blank)d[n]='';}return d;}
function normalized(meta,input,existing,user){const data=existing?{...existing}:defaults(meta);for(const [n,f] of Object.entries(meta.fields)){if(f.readonly||['created_by','recorded_by','uploaded_by'].includes(n)||n==='user'&&meta.table==='notifications_notification')continue;if(n==='password')continue;if(n in input)data[n]=input[n];}
 for(const n of ['created_by','recorded_by','uploaded_by'])if(n in meta.fields&&!existing)data[n]=user.id;
 if(meta.table==='notifications_notification'&&!existing)data.user=user.id;
 if('updated_at' in meta.fields)data.updated_at=now();
 if(meta.table==='production_productionorder'){data.total_amount=orderTotal(data.quantity,data.rate);data.paid_amount=existing?.paid_amount||'0.00';data.remaining_balance=money(scaled(data.total_amount)-scaled(data.paid_amount));data.is_financially_closed=Number(scaled(data.total_amount)<=scaled(data.paid_amount)&&['delivered','closed'].includes(data.status));if(!existing)data.order_number='ORD-'+new Date().getFullYear()+'-'+uuid().slice(0,8).toUpperCase();}
 if(meta.table==='finance_payment')data.resulting_balance=existing?.resulting_balance||'0.00';
 if(meta.table==='scheduling_appointment'){interval(data);data.duration=new Date(Date.parse(data.end_time)-Date.parse(data.start_time)).toISOString().slice(11,19);}
 if(meta.table==='scheduling_resourceblock')interval({...data,buffer_before:'00:00:00',buffer_after:'00:00:00'});
 for(const [n,f] of Object.entries(meta.fields)){
 if(f.type==='ManyToManyField'||n==='password')continue;let v=data[n];if(v===''&&f.null)v=data[n]=null;
 if(v===undefined||v===null){if(!f.null)fail(400,n+' is required',{[n]:['This field is required.']});continue;}
 if(f.type==='BooleanField')data[n]=v===true||v===1||v==='true'||v==='1'?1:0;
 if(['ForeignKey','OneToOneField','IntegerField','PositiveIntegerField'].includes(f.type)){if(!Number.isSafeInteger(Number(v))||Number(v)<(['IntegerField','PositiveIntegerField'].includes(f.type)?0:1))fail(400,'Invalid '+n);data[n]=Number(v);}
 if(f.type==='DecimalField'){data[n]=money(scaled(v));if(['amount','quantity','rate','hours'].includes(n)&&scaled(v)<=0)fail(400,n+' must be positive');}
 if(f.type==='DateTimeField'){if(!/(Z|[+-]\d{2}:\d{2})$/.test(String(v))||!Number.isFinite(Date.parse(v)))fail(400,'Invalid '+n);data[n]=new Date(v).toISOString();}
 if(f.type==='DateField'&&(!/^\d{4}-\d{2}-\d{2}$/.test(String(v))||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==String(v)))fail(400,'Invalid '+n);
 if(f.max_length&&String(v).length>f.max_length)fail(400,n+' is too long');if(f.choices&&!(f.blank&&data[n]==='')&&!f.choices.includes(data[n]))fail(400,'Invalid '+n);
 if(!f.blank&&f.type==='CharField'&&!String(v).trim())fail(400,n+' is required');
 }
 if(meta.table==='accounts_client'){if(!/^[A-Za-z\u0600-\u06FF][A-Za-z\u0600-\u06FF\s'\-]*$/.test(data.name))fail(400,'Name must contain letters');if(!/^(010|011|012|015)\d{8}$/.test(data.primary_phone))fail(400,'Mobile number must be 11 digits starting 010, 011, 012 or 015');}

 return data;}
function dbValue(v,f){if(f.type==='BooleanField')return v==null?null:Number(v);return f.type==='JSONField'?JSON.stringify(v):v;}
function writeStmt(env,meta,data,id){const keys=Object.keys(meta.fields).filter(n=>meta.fields[n].type!=='ManyToManyField'&&data[n]!==undefined);const vals=keys.map(n=>dbValue(data[n],meta.fields[n]));return id?stmt(env,`UPDATE ${meta.table} SET ${keys.map(n=>q(n)+'=?').join(',')} WHERE id=?`,...vals,id):stmt(env,`INSERT INTO ${meta.table} (${keys.map(q).join(',')}) VALUES (${keys.map(()=>'?').join(',')})`,...vals);}
async function relations(env,meta,data,input,owner){const ops=[];for(const [n,f] of Object.entries(meta.fields)){if(f.type!=='ManyToManyField')continue;let values=input[n];if(n==='tags'&&input.tags_input){values=[];for(const name of input.tags_input){let tag=await first(env,'SELECT id FROM accounts_clienttag WHERE name=?',name.trim());if(!tag){const t=defaults(schema['accounts/client-tags']);t.name=name.trim();const r=await writeStmt(env,schema['accounts/client-tags'],t).run();tag={id:r.meta.last_row_id};}values.push(tag.id);}}
 if(n==='resources'&&meta.table==='scheduling_appointment')values=values?.length?values:[1];if(values===undefined)continue;if(!Array.isArray(values))fail(400,n+' must be a list');const table=meta.table+'_'+n;ops.push(stmt(env,`DELETE FROM ${table} WHERE owner_id=${owner}`));for(const target of new Set(values.map(Number))){if(!Number.isSafeInteger(target)||target<1)fail(400,'Invalid relation');ops.push(stmt(env,`INSERT INTO ${table}(owner_id,target_id) VALUES (${owner},?)`,target));}}
 return ops;}
async function lookup(env,table){env.LOOKUPS ||= {};if(!env.LOOKUPS[table])env.LOOKUPS[table]=all(env,'SELECT * FROM '+table);return env.LOOKUPS[table];}
async function decorate(env,route,row,origin){const meta=schema[route],d={...row};delete d.password;delete d.amount_cents;delete d.total_cents;const find=async(table,id)=>(await lookup(env,table)).find(r=>r.id===id);
 for(const [n,f] of Object.entries(meta.fields)){if(f.type==='BooleanField')d[n]=Boolean(d[n]);if(f.type==='JSONField'&&typeof d[n]==='string'){try{d[n]=JSON.parse(d[n]);}catch{d[n]={};}}if(f.type==='ManyToManyField')d[n]=(await lookup(env,meta.table+'_'+n)).filter(r=>r.owner_id===row.id).map(x=>x.target_id);}
 if(route==='accounts/clients'){const tags=await lookup(env,'accounts_clienttag');d.tags=tags.filter(t=>d.tags.includes(t.id));const os=(await lookup(env,'production_productionorder')).filter(o=>o.client===d.id);d.total_revenue=money(os.reduce((n,o)=>n+scaled(o.total_amount),0));d.outstanding_balance=money(os.filter(o=>o.status!=='cancelled').reduce((n,o)=>n+Math.round(Number(o.remaining_balance)*100),0));d.session_count=(await lookup(env,'scheduling_appointment')).filter(a=>a.client===d.id&&['confirmed','completed'].includes(a.status)).length;}
 if(d.client)d.client_name=(await find('accounts_client',d.client))?.name;
 if(d.package)d.package_name=(await find('production_package',d.package))?.name;
 if(d.order)d.order_number=(await find('production_productionorder',d.order))?.order_number;
 if(route==='finance/expenses')d.category_name=(await find('finance_expensecategory',d.category))?.name;
 if(route==='accounts/staff'){const u=await find('accounts_user',d.user);d.user=u?userView(u):null;}
 if(d.staff){const member=await find('accounts_staffmember',d.staff),u=member?await find('accounts_user',member.user):null;d.staff_name=u?(u.first_name+' '+u.last_name).trim()||u.username:'';}
 if(route==='toolkit/service-profiles'){d.recommended_packages_detail=(await lookup(env,'production_package')).filter(p=>d.recommended_packages.includes(p.id));d.suggested_script_detail=d.suggested_script?await find('toolkit_scripttemplate',d.suggested_script):null;}
 if(route==='toolkit/report-drafts'){d.file_url=origin+'/files/report/'+d.token;d.public_view_url=origin+'/r/'+d.token+'/';d.qr_value=d.public_view_url;d.created_by_name=(await find('accounts_user',d.created_by))?.username;delete d.file;}
 if(route==='finance/attachments')d.file=origin+'/files/attachment/'+d.share_token;
 return d;}

async function mutate(env,route,input,id,user,trusted={},options={}){const meta=schema[route];if(route==='accounts/users')admin(user);const old=id?await first(env,`SELECT * FROM ${meta.table} WHERE id=?`,id):null;if(id&&!old)fail(404,'Record not found');if(route==='accounts/users'&&old?.id===user.id&&input.is_active===false)fail(400,'Cannot disable your own account');
 let password;if(route==='accounts/users'&&input.password){if(String(input.password).length<12)fail(400,'Password must have at least 12 characters');password=await passwordHash(input.password);}if(route==='accounts/users'&&!old&&!password)fail(400,'Password is required');
 const data={...normalized(meta,input,old,user),...trusted};if(password)data.password=password;
 const ops=options.setup?[stmt(env,'INSERT INTO setup_lock(id) VALUES(1)')]:[]; // Use an explicit allocated id in one atomic batch to keep parent/link inserts together.
 const newId=id||Number((await first(env,`SELECT COALESCE(MAX(id),0)+1 AS n FROM ${meta.table}`)).n);
 if(!id){const keys=Object.keys(meta.fields).filter(n=>meta.fields[n].type!=='ManyToManyField'&&data[n]!==undefined);ops.push(stmt(env,`INSERT INTO ${meta.table} (id,${keys.map(q).join(',')}) VALUES (?,${keys.map(()=>'?').join(',')})`,newId,...keys.map(n=>dbValue(data[n],meta.fields[n]))));}else{
 // Remove links before changing time; links are reinserted with DB conflict checks in the same batch.
 if(route==='scheduling/appointments')ops.push(stmt(env,'DELETE FROM scheduling_appointment_resources WHERE owner_id=?',id));ops.push(writeStmt(env,meta,data,id));}
 if(route==='scheduling/appointments'&&!('resources' in input)&&old)input.resources=(await all(env,'SELECT target_id FROM scheduling_appointment_resources WHERE owner_id=?',id)).map(r=>r.target_id);
 ops.push(...await relations(env,meta,data,input,String(newId)));
 if(route==='finance/payments'&&!id){const n=defaults(schema.notifications);Object.assign(n,{user:user.id,type:'new_deposit',title:'Payment recorded',title_ar:'تم تسجيل دفعة',message:'EGP '+data.amount+' recorded for order '+data.order,message_ar:'تم تسجيل دفعة '+data.amount+' جنيه',deep_link:'/payments',idempotency_key:'payment:'+data.payment_id});ops.push(writeStmt(env,schema.notifications,n));}
ops.push(stmt(env,'INSERT INTO audit_log(user_id,action,record_id,created_at) VALUES (?,?,?,?)',user.id,(id?'update:':'create:')+route,String(newId),now()));
 try{await env.DB.batch(ops);env.LOOKUPS={};}catch(e){if(/UNIQUE constraint failed.*\.id/.test(e.message)&&!id)return mutate(env,route,input,id,user,trusted,options);throw e;}
 return decorate(env,route,await first(env,`SELECT * FROM ${meta.table} WHERE id=?`,newId),env.ORIGIN);}
async function login(req,env){const b=await body(req);const username=String(b.username||'').slice(0,150),key=await digest((req.headers.get('CF-Connecting-IP')||'unknown')+':'+username),t=Date.now();const limiter=await first(env,'SELECT * FROM login_limits WHERE key=?',key);if(limiter?.reset_at>t&&limiter.attempts>=10)fail(429,'Too many attempts. Try again in 15 minutes');await stmt(env,'INSERT INTO login_limits(key,attempts,reset_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN reset_at>? THEN attempts+1 ELSE 1 END,reset_at=CASE WHEN reset_at>? THEN reset_at ELSE ? END',key,t+900000,t,t,t+900000).run();const u=await first(env,'SELECT * FROM accounts_user WHERE username=? AND is_active=1',username);const valid=await verifyPassword(String(b.password||''),u?.password||await passwordHash('dummy-password'));if(!u||!valid)fail(400,'Unable to log in with provided credentials');await stmt(env,'DELETE FROM login_limits WHERE key=?',key).run();const token=uuid()+uuid(),expires=t+7*86400000;await stmt(env,'INSERT INTO sessions VALUES (?,?,?)',await digest(token),u.id,expires).run();return json({token,user:userView(u)},200,{'Set-Cookie':`ss_session=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=604800`});}
async function bootstrap(req,env){if(!env.BOOTSTRAP_TOKEN)fail(404,'Not found');const supplied=req.headers.get('Authorization')?.replace(/^Bearer /,'')||'';if(!equal(await digest(supplied),await digest(env.BOOTSTRAP_TOKEN)))fail(403,'Invalid setup token');if(await first(env,'SELECT id FROM accounts_user LIMIT 1'))fail(409,'Setup already completed');const b=await body(req);if(!b.username||String(b.password||'').length<12)fail(400,'Username and a password of at least 12 characters are required');const u=await mutate(env,'accounts/users',{username:b.username,password:b.password,role:'owner',first_name:'',last_name:'',email:''},null,{id:1,role:'owner'},{},{setup:true});await seed(env,{id:u.id,role:'owner'});return json({status:'created',username:u.username},201);}
async function seed(env,u){const items=[['finance/settings',{name:'SMART SHOOTS'}],['scheduling/resources',{name:'Studio',type:'venue'}],...['Internet','Office Rent','Electricity'].map((name,i)=>['finance/expense-categories',{name,category_type:['internet','office_rent','electricity'][i],is_recurring:true,recurring_interval:'monthly'}]),...['Learning','Reels','Outdoor'].map(name=>['accounts/client-tags',{name}]),['production/packages',{name:'Learning recording',type:'hourly_learning',default_rate:'250.00',unit:'hour'}],['production/packages',{name:'Reels per minute',type:'per_minute_reels',default_rate:'0.00',unit:'minute'}],['production/packages',{name:'Outdoor shoot',type:'outdoor_shoot',default_rate:'0.00',unit:'session'}]];const ops=[];for(const [route,b] of items)if(!(await first(env,`SELECT id FROM ${schema[route].table} WHERE name=?`,b.name)))ops.push(writeStmt(env,schema[route],normalized(schema[route],b,null,u)));if(ops.length)await env.DB.batch(ops);}
async function report(env,kind,url){const [payments,expenses,orders,clients,appts]=await Promise.all(['finance_payment','finance_expense','production_productionorder','accounts_client','scheduling_appointment'].map(t=>all(env,'SELECT * FROM '+t)));const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),month=today.slice(0,7),sum=(a,k)=>money(a.reduce((n,x)=>n+Math.round(Number(x[k]||0)*100),0));
 if(kind==='dashboard'){const p=payments.filter(x=>x.payment_date.startsWith(month)&&x.payment_date<=today),e=expenses.filter(x=>x.expense_date.startsWith(month)&&x.expense_date<=today);const counts={};appts.forEach(a=>counts[a.status]=(counts[a.status]||0)+1);return {monthly_revenue:sum(p,'amount'),collected_payments:sum(p,'amount'),outstanding_balance:sum(orders.filter(o=>o.status!=='cancelled'),'remaining_balance'),monthly_expenses:sum(e,'amount'),net_cash_flow:money(p.reduce((s,x)=>s+scaled(x.amount),0)-e.reduce((s,x)=>s+scaled(x.amount),0)),upcoming_appointments:appts.filter(a=>a.start_time>=now()&&['pending','confirmed'].includes(a.status)).length,pending_production:orders.filter(o=>['pending','in_progress'].includes(o.status)).length,active_clients:clients.filter(c=>c.is_active).length,appointment_status_breakdown:Object.entries(counts).map(([status,count])=>({status,count,label:status.replace('_',' ')})),recent_payments:payments.sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,5).map(p=>({id:p.payment_id,amount:p.amount,date:p.payment_date,client:clients.find(c=>c.id===p.client)?.name})),recent_orders:orders.sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,5).map(o=>({id:o.order_id,number:o.order_number,status:o.status,client:clients.find(c=>c.id===o.client)?.name}))};}
 const days=Math.max(1,Math.min(366,Number(url.searchParams.get('days'))||30)),dates=[];for(let i=days-1;i>=0;i--)dates.push(new Date(Date.parse(today+'T12:00:00Z')-i*86400000).toISOString().slice(0,10));const start=dates[0],ps=payments.filter(p=>p.payment_date>=start&&p.payment_date<=today),es=expenses.filter(e=>e.expense_date>=start&&e.expense_date<=today),os=orders.filter(o=>o.order_date>=start&&o.order_date<=today&&o.status!=='cancelled');return {daily_data:dates.map(date=>{const p=ps.filter(x=>x.payment_date===date),e=es.filter(x=>x.expense_date===date);return {date,revenue:sum(p,'amount'),expenses:sum(e,'amount'),net:money(p.reduce((s,x)=>s+scaled(x.amount),0)-e.reduce((s,x)=>s+scaled(x.amount),0)),new_clients:clients.filter(c=>c.created_at.slice(0,10)===date).length,total_clients:clients.filter(c=>c.created_at.slice(0,10)<=date).length};}),total_revenue:sum(ps,'amount'),total_expenses:sum(es,'amount'),total_orders:os.length,total_order_value:sum(os,'total_amount'),new_clients_in_range:clients.filter(c=>c.created_at.slice(0,10)>=start&&c.created_at.slice(0,10)<=today).length};}
async function backup(env){const data={};for(const [route,m] of Object.entries(schema)){if(route==='accounts/users')continue;const rows=await all(env,'SELECT * FROM '+m.table);const joins={};for(const [n,f] of Object.entries(m.fields))if(f.type==='ManyToManyField')joins[n]=await all(env,`SELECT * FROM ${m.table}_${n}`);data[m.model]=[];for(const row of rows){const fields={};for(const [n,f] of Object.entries(m.fields)){if(f.type==='ManyToManyField')fields[n]=joins[n].filter(x=>x.owner_id===row.id).map(x=>x.target_id);else fields[n]=f.type==='JSONField'?JSON.parse(row[n]):f.type==='BooleanField'?Boolean(row[n]):row[n];}data[m.model].push({model:m.model,pk:row.id,fields});}}return data;}
async function restore(env,data,user){admin(user);if(!data||typeof data!=='object'||Array.isArray(data))fail(400,'Invalid backup format');
 // Import only into an empty business database. Never overwrite cloud records or login accounts.
 for(const table of ['accounts_client','production_productionorder','finance_payment','finance_expense','accounts_staffmember'])if((await first(env,'SELECT COUNT(*) AS n FROM '+table)).n)fail(409,'Import requires an empty business database. Existing data was not changed.');
 const allowed=new Map(Object.entries(schema).filter(([r])=>r!=='accounts/users').map(([r,m])=>[m.model,{route:r,meta:m}])),ops=[],links=[],fileWarnings=[];let count=0;
 const priorities=['accounts.clienttag','accounts.client','accounts.staffmember','accounts.staffevaluation','production.package','production.productionorder','production.productionassignment','production.delivery','production.timelog','scheduling.resource','scheduling.appointment','scheduling.resourceblock','finance.expensecategory','finance.expense','finance.payment','toolkit.scripttemplate','toolkit.serviceprofile'];
 const staffMap=new Map();
 const sourceStaff=Object.entries(data).find(([k])=>k.toLowerCase()==='accounts.staffmember')?.[1]||[];
 let uid=(await first(env,'SELECT COALESCE(MAX(id),0)+1 AS n FROM accounts_user')).n;
 for(const source of sourceStaff){const oldId=source.fields.user;if(staffMap.has(oldId))continue;const newId=uid++;staffMap.set(oldId,newId);const m=schema['accounts/users'],u=defaults(m);Object.assign(u,{username:'migrated-staff-'+oldId,password:await passwordHash(uuid()+uuid()),is_active:0,role:'staff',first_name:'',last_name:''});const keys=Object.keys(u);ops.push(stmt(env,`INSERT INTO accounts_user(id,${keys.map(q).join(',')}) VALUES (?,${keys.map(()=>'?').join(',')})`,newId,...keys.map(n=>dbValue(u[n],m.fields[n]))));}
 for(const [label,records] of Object.entries(data).sort(([a],[b])=>(priorities.indexOf(a.toLowerCase())<0?50:priorities.indexOf(a.toLowerCase()))-(priorities.indexOf(b.toLowerCase())<0?50:priorities.indexOf(b.toLowerCase())))){const item=allowed.get(label.toLowerCase());if(!item){if(label.toLowerCase()==='accounts.user')continue;fail(400,'Unsupported backup model: '+label);}if(!Array.isArray(records))fail(400,'Invalid records for '+label);for(const rec of records){if(!Number.isSafeInteger(rec.pk)||rec.pk<1||!rec.fields)fail(400,'Invalid backup record');const {route,meta}=item;const input={...rec.fields};if(route==='accounts/staff')input.user=staffMap.get(input.user);if(route.startsWith('notifications'))input.user=user.id;
 let d=normalized(meta,input,null,user);for(const [n,f] of Object.entries(meta.fields)){if(f.readonly&&n in input)d[n]=input[n];if(['created_by','recorded_by','uploaded_by'].includes(n))d[n]=user.id;}
 if(route==='production/orders'){d.total_amount=orderTotal(d.quantity,d.rate);d.paid_amount='0.00';d.remaining_balance=d.total_amount;d.is_financially_closed=0;}
 if(route==='finance/payments')d.resulting_balance='0.00';
 if(['finance/attachments','toolkit/report-drafts'].includes(route)){if(!String(d.file).startsWith('uploads/')||!(await env.FILES.get(d.file))){fileWarnings.push(d.filename||d.title);continue;}}
 const keys=Object.keys(meta.fields).filter(n=>meta.fields[n].type!=='ManyToManyField'&&d[n]!==undefined);ops.push(stmt(env,`INSERT INTO ${meta.table}(id,${keys.map(q).join(',')}) VALUES (?,${keys.map(()=>'?').join(',')}) ON CONFLICT(id) DO UPDATE SET ${keys.map(n=>q(n)+'=excluded.'+q(n)).join(',')}`,rec.pk,...keys.map(n=>dbValue(d[n],meta.fields[n]))));for(const [n,f] of Object.entries(meta.fields))if(f.type==='ManyToManyField'){let ids=input[n]||[];if(route==='scheduling/appointments'&&!ids.length)ids=[1];links.push(stmt(env,`DELETE FROM ${meta.table}_${n} WHERE owner_id=?`,rec.pk));for(const target of ids)links.push(stmt(env,`INSERT INTO ${meta.table}_${n} VALUES (?,?)`,rec.pk,target));}count++;}}
 if(ops.length+links.length>500)fail(400,'Backup exceeds the atomic import limit (500 statements). Split migration with a reviewed data migration script.');
 // Reorder by table dependencies; FK checks are deferred only inside this atomic batch.

 await env.DB.batch([stmt(env,'PRAGMA defer_foreign_keys=ON'),stmt(env,'INSERT INTO restore_lock(id) VALUES (1)'),stmt(env,"INSERT INTO import_guard(id) VALUES (CASE WHEN EXISTS(SELECT 1 FROM accounts_client) OR EXISTS(SELECT 1 FROM production_productionorder) OR EXISTS(SELECT 1 FROM finance_payment) THEN 0 ELSE 1 END)"),...ops,...links,stmt(env,'DELETE FROM restore_lock WHERE id=1'),stmt(env,'DELETE FROM import_guard WHERE id=1')]);return {status:'success',restored:count,files_to_reupload:fileWarnings,staff_accounts:staffMap.size,notes:'Local files are not included in JSON backups; upload them again. Imported staff accounts are disabled until an administrator sets their name and password.'};}
async function upload(req,env,route,id,user){const form=await req.formData(),files=form.getAll('file').length?form.getAll('file'):form.getAll('files');if(!files.length)fail(400,'No file provided');const records=[];for(const file of files){if(typeof file==='string')fail(400,'Invalid file');if(file.size>25*1024*1024)fail(413,'Maximum file size is 25 MB');const ext=file.name.split('.').pop().toLowerCase();if(route==='toolkit/report-drafts'&&!['html','htm','doc','docx'].includes(ext))fail(400,'Report drafts accept HTML or Word files');const token=uuid(),key='uploads/'+token+'/'+file.name.replace(/[^\w.\-]/g,'_');await env.FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type||'application/octet-stream'}});const input=Object.fromEntries([...form.entries()].filter(([,v])=>typeof v==='string'));input.file=key;if(route==='finance/attachments'){Object.assign(input,{filename:file.name,file_type:file.type||'application/octet-stream',file_size:file.size,share_token:token});}else Object.assign(input,{file_type:ext==='htm'?'html':ext,token});
 // Derived upload metadata is server controlled, supplied after validation through a scoped schema copy.
 const trusted=Object.fromEntries(['file_type','token','share_token','filename','file_size'].filter(n=>n in input).map(n=>[n,input[n]]));
 try{records.push(await mutate(env,route,input,id,user,trusted));}catch(e){await env.FILES.delete(key);throw e;}}
 return json(records.length===1&&!req.url.includes('/bulk/')?records[0]:records,201);}
async function fileResponse(req,env,url,user){const parts=url.pathname.split('/').filter(Boolean);let row;const type=parts[1],token=parts[2];if(type==='report'){row=await first(env,'SELECT * FROM toolkit_reportdraft WHERE token=? AND is_active=1',token);}else if(type==='attachment'){row=await first(env,'SELECT * FROM finance_attachment WHERE share_token=?',token);if(row&&!row.is_shareable&&!user)await authenticate(req,env);}if(!row)fail(404,'File not found');const obj=await env.FILES.get(row.file);if(!obj)fail(404,'File is not uploaded to cloud storage');const h=new Headers({'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox allow-scripts allow-downloads; default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval'"});obj.writeHttpMetadata(h);if(type==='report'&&row.file_type==='html')h.set('Content-Type','text/html; charset=utf-8');else h.set('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(row.filename||row.title+'.'+row.file_type)}`);return new Response(obj.body,{headers:h});}
async function publicReport(req,env,url){const token=url.pathname.match(/\/r\/([^/]+)/)?.[1]||url.pathname.match(/report-drafts\/([^/]+)\/open/)?.[1];const row=await first(env,'SELECT * FROM toolkit_reportdraft WHERE token=? AND is_active=1',token);if(!row)fail(404,'Report not found');if(url.searchParams.get('preview')!=='1')await stmt(env,'UPDATE toolkit_reportdraft SET view_count=view_count+1 WHERE id=?',row.id).run();const src='/files/report/'+encodeURIComponent(token);const title=String(row.title).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]));return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>html,body,iframe{margin:0;width:100%;height:100%;border:0}body{font-family:system-ui;background:#071426;color:white}a{color:#7dd3fc}main{padding:32px}</style></head><body>${row.file_type==='html'?`<iframe sandbox="allow-scripts allow-downloads" src="${src}" title="${title}"></iframe>`:`<main><h1>${title}</h1><a href="${src}">Download Word report / تحميل التقرير</a></main>`}</body></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; style-src 'unsafe-inline'; frame-src 'self'; frame-ancestors 'self'"}});}
async function routeRequest(req,env){const url=new URL(req.url);env={...env,ORIGIN:url.origin};const path=url.pathname.replace(/\/+$/,'')||'/';const method=req.method.toUpperCase();if(path==='/api/health')return json({status:'ok',backend:'cloudflare',database:!!(await first(env,'SELECT 1 AS ok'))});if(path==='/api/setup'&&method==='POST')return bootstrap(req,env);if(path==='/api/accounts/auth/login'&&method==='POST')return login(req,env);if(path.startsWith('/r/')||/\/report-drafts\/[^/]+\/open$/.test(path)){if(method!=='GET')fail(405,'Method not allowed');return publicReport(req,env,url);}if(path.startsWith('/files/')){if(method!=='GET')fail(405,'Method not allowed');return fileResponse(req,env,url);}
 if(!path.startsWith('/api/'))return env.ASSETS.fetch(req);const user=await authenticate(req,env);
 if(!['GET','HEAD','OPTIONS'].includes(method)){const origin=req.headers.get('Origin');if(origin&&origin!==url.origin)fail(403,'Cross-origin writes are not allowed');}
 if(path==='/api/accounts/auth/me')return json(userView(user));if(path==='/api/accounts/auth/logout'&&method==='POST'){const raw=req.headers.get('Authorization')?.replace(/^(Token|Bearer) /,'')||req.headers.get('Cookie')?.match(/ss_session=([^;]+)/)?.[1];if(raw)await stmt(env,'DELETE FROM sessions WHERE token_hash=?',await digest(raw)).run();return json({status:'logged_out'},200,{'Set-Cookie':'ss_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'});}
 if(path==='/api/finance/backup'&&method==='GET'){admin(user);return json(await backup(env),200,{'Content-Disposition':'attachment; filename="smart_shoots_backup.json"'});}if(path==='/api/finance/restore'&&method==='POST'){admin(user);const b=await body(req);let data=b;if(b instanceof FormData){const f=b.get('file');if(!f||typeof f==='string')fail(400,'Backup file is required');if(f.size>10*1024*1024)fail(413,'Backup exceeds 10 MB');try{data=JSON.parse(await f.text());}catch{fail(400,'Backup must be valid JSON');}}return json(await restore(env,data,user));}
 if(['/api/reports/dashboard','/api/reports/financial'].includes(path)&&method==='GET')return json(await report(env,path.split('/').pop(),url));
 if(path==='/api/assistant/query'&&method==='POST'){const b=await body(req),r=await report(env,'dashboard',url);const ar=/[\u0600-\u06ff]/.test(b.query||'');return json({response:ar?`العملاء النشطون: ${r.active_clients}. الإيرادات الشهرية: ${r.monthly_revenue} جنيه. الرصيد المستحق: ${r.outstanding_balance} جنيه. صافي التدفق النقدي: ${r.net_cash_flow} جنيه.`:`Active clients: ${r.active_clients}. Monthly revenue: EGP ${r.monthly_revenue}. Outstanding: EGP ${r.outstanding_balance}. Net cash flow: EGP ${r.net_cash_flow}.`,mode:'business-summary'});}
 if(path==='/api/notifications/mark_all_read'&&method==='POST'){await stmt(env,'UPDATE notifications_notification SET is_read=1,read_at=? WHERE user=?',now(),user.id).run();return json({status:'success'});}
 const sub=path.slice(5);let route=Object.keys(schema).sort((a,b)=>b.length-a.length).find(r=>sub===r||sub.startsWith(r+'/'));if(!route)fail(404,'API endpoint not found');const meta=schema[route],tail=sub.slice(route.length).replace(/^\//,''),id=tail?Number(tail.split('/')[0]):null;
 if(route==='accounts/users')admin(user);
 if(route==='finance/attachments'&&tail==='bulk'&&method==='POST')return upload(req,env,route,null,user);
 if(route==='accounts/clients'&&/^\d+\/full_details$/.test(tail)&&method==='GET'){const c=await first(env,'SELECT * FROM accounts_client WHERE id=?',id);if(!c)fail(404,'Client not found');const d={client:await decorate(env,route,c,url.origin)};for(const [key,r,field] of [['phones','accounts/phones','client'],['orders','production/orders','client'],['sessions','scheduling/appointments','client'],['payments','finance/payments','client'],['attachments','finance/attachments','client']])d[key]=await all(env,`SELECT * FROM ${schema[r].table} WHERE ${q(field)}=?`,id);return json(d);}
 if(tail&&(!Number.isSafeInteger(id)||id<=0||tail.includes('/')))fail(404,'Record not found');
 if(['POST','PUT','PATCH'].includes(method)){if(method==='POST'&&id||method!=='POST'&&!id)fail(405,'Method not allowed');if(['finance/attachments','toolkit/report-drafts'].includes(route)&&req.headers.get('Content-Type')?.includes('multipart/form-data'))return upload(req,env,route,id,user);const b=await body(req);if(b instanceof FormData)fail(400,'This endpoint accepts JSON');if(route==='notifications')fail(405,'Notifications are generated by the cloud service');return json(await mutate(env,route,b,id,user),id?200:201);}
 if(method==='DELETE'){if(!id)fail(405,'Record id required');const existing=await first(env,`SELECT * FROM ${meta.table} WHERE id=?`,id);if(!existing)fail(404,'Record not found');if(route==='accounts/users'&&id===user.id)fail(400,'Cannot delete your account');if(route==='notifications'&&existing.user!==user.id)fail(404,'Record not found');await env.DB.batch([stmt(env,`DELETE FROM ${meta.table} WHERE id=?`,id),stmt(env,'INSERT INTO audit_log(user_id,action,record_id,created_at) VALUES (?,?,?,?)',user.id,'delete:'+route,String(id),now())]);if(['finance/attachments','toolkit/report-drafts'].includes(route))await env.FILES.delete(existing.file);return new Response(null,{status:204});}
 if(method!=='GET')fail(405,'Method not allowed');if(id){const row=await first(env,`SELECT * FROM ${meta.table} WHERE id=?`,id);if(!row||route==='notifications'&&row.user!==user.id)fail(404,'Record not found');return json(await decorate(env,route,row,url.origin));}
 const where=[],params=[];if(route==='notifications'){where.push('user=?');params.push(user.id);}for(const [k,v] of url.searchParams){if(!(k in meta.fields)||meta.fields[k].type==='ManyToManyField')continue;where.push(q(k)+'=?');params.push(meta.fields[k].type==='BooleanField'?Number(v==='true'||v==='1'):v);}
 if(['toolkit/scripts','toolkit/service-profiles','toolkit/report-drafts'].includes(route)&&!url.searchParams.has('is_active'))where.push('is_active=1');
 const search=url.searchParams.get('search');if(search){const cols=['name','title','primary_phone','email','order_number','reference','description','body'].filter(n=>n in meta.fields);if(cols.length){where.push('('+cols.map(n=>q(n)+' LIKE ?').join(' OR ')+')');params.push(...cols.map(()=>'%'+search+'%'));}}
 const clause=where.length?' WHERE '+where.join(' AND '):'',count=(await first(env,'SELECT COUNT(*) AS n FROM '+meta.table+clause,...params)).n,size=Math.min(100,Math.max(1,Number(url.searchParams.get('page_size'))||100)),page=Math.max(1,Number(url.searchParams.get('page'))||1);let ordering=url.searchParams.get('ordering')||(meta.fields.name?'name':'-id');const desc=ordering.startsWith('-');ordering=ordering.replace(/^-/,'');if(ordering!=='id'&&!(ordering in meta.fields))ordering='id';const rows=await all(env,`SELECT * FROM ${meta.table}${clause} ORDER BY ${q(ordering)} ${desc?'DESC':'ASC'} LIMIT ? OFFSET ?`,...params,size,(page-1)*size);const link=p=>{const u=new URL(url);u.searchParams.set('page',p);return u.toString();};return json({count,next:page*size<count?link(page+1):null,previous:page>1?link(page-1):null,results:await Promise.all(rows.map(r=>decorate(env,route,r,url.origin)))});
}
export default {
 async fetch(req,env){try{return await routeRequest(req,env);}catch(e){if(e instanceof HttpError)return json({detail:e.message,...e.fields},e.status);const msg=String(e.message);if(/constraint|already booked|blocked|mismatch|Cannot change|exceeds order|below collected/.test(msg))return json({detail:/FOREIGN KEY/.test(msg)?'Related record is missing or is in use':/already booked|blocked/.test(msg)?'Booking conflict: resource is booked or blocked, including buffers':/UNIQUE/.test(msg)?'This record already exists':'Data integrity validation failed'},409);console.error('Worker request failed',req.method,new URL(req.url).pathname,e);return json({detail:'Cloud service error. Please retry or check Worker logs.'},500);}},
 async scheduled(event,env,ctx){ctx.waitUntil((async()=>{await stmt(env,'DELETE FROM sessions WHERE expires_at<?',Date.now()).run();await stmt(env,'DELETE FROM login_limits WHERE reset_at<?',Date.now()).run();const data=await backup(env);await env.FILES.put('backups/'+now().slice(0,10)+'.json',JSON.stringify(data),{httpMetadata:{contentType:'application/json'}});})());}
};
